"""Add user bio

Revision ID: 4f88c225920f
Revises: e59704a0f553
Create Date: 2023-11-05 00:05:20.817654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f88c225920f"
down_revision: Union[str, None] = "e59704a0f553"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("bio", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "bio")
    # ### end Alembic commands ###
