"""Add image uploaded field

Revision ID: 9c37fc7757b4
Revises: 4f88c225920f
Create Date: 2023-11-17 07:55:53.865807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c37fc7757b4"
down_revision: Union[str, None] = "4f88c225920f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image", sa.Column("uploaded", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("image", "uploaded")
    # ### end Alembic commands ###
